#!/bin/bash

export HOME=/var/tmp
export FACTER_FQDN=$(uname -n)
export FACTER_IPADDRESS=127.0.0.1

PUPPET=$(which puppet)
PFLAGS="--modulepath=/etc/puppet/modules --parser future"
FPFILE=$1

if [ $# -eq 1 ]; then
  read -t 3 INPUT
  export FACTER_INPUT=${INPUT}
else
  shift
  export FACTER_INPUT=$*
fi

if [ $? -eq 0 ]; then
  ${PUPPET} apply ${PFLAGS} ${FPFILE}
else
  echo "Cannot find puppet executable, exiting."
  exit 1
fi
