#!/usr/bin/finger-puppet

/*

  Add entry to /etc/hosts if it doesn't exist

  Usage: echo "<hostname> <ip>" | ./add_hosts.pp

*/

$host = split($::input, '\s')

host { $host[0]:
  ensure  => present,
  ip      => $host[1],
  comment => "Automatically generated by finger-puppet."
}
